compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
  libc:
    - glibc
    - musl
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.7.0.cjs
